#!/bin/sh -e

amixer cset name='Left Input Mixer L2 Switch' on
amixer cset name='Right Input Mixer R2 Switch' on
amixer cset name='Headphone Playback Volume' 100%
amixer cset name='PCM Volume' 100%
amixer cset name='Input PGA Volume' 100%

[ -d /usr/share/vosk/vosk-model-small-en-us-0.15 -a ! -e /usr/share/vosk/model ] && ln -sf vosk-model-small-en-us-0.15 /usr/share/vosk/model
[ 0 -ne `cat /usr/share/vosk/model/README | grep 'Chinese Vosk model' | wc -l` ] && export LC_ALL=zh_CN.utf8
arecord -f S16_LE -r 24000 -t wav | test_vosk
